# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Andrii Romanenko
# Description of the Site
description: portfolio
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, portfolio, Romanenko, Andrii, Frontend, HTML, CSS, JavaScript
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/brilliantic/My_Portfolio/master/assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# https://lh3.googleusercontent.com/pw/AIL4fc8podUmLtZSW9WjQp6DMK1FFztvO2s7RA9QlmXs0bGbJ93d_16-F7d5SEHDbsbls5cUXzAjBdYlRiJsbgXZbj0nSXjeLNwGAVWcZ61x44CDH2khUeDQjyQ0XLAReP_1awxuGOGgLHLLxzB-kpKnyPhpTsASHakhOPMHcVW05Qf1ERgiRAnhLu71FihAH-NVPs2SOte3WCpGUEzHtWgnvGOWt4wgUIsC1wpaCb_iOp_lg9tckXk6LI7C8sxgRaiSWELpWy7bIaBA5_ajKDB66VJ0z2eM2ZCHyHdE1-Je85PVHixvH-y15kfrngBMvF3XwTvGytBjW7j1UZ14mGIuPuarw7qkbZbqx0aX7gfw6G1MYtP_4lTSEW7unI_SsikKrRUSsgTRJqvYlBcUSmqiDHiZ6uQOXN5Ll1IwOCskew6XNIcHhJ6G9_c_cCd8suUUmbM8nhdBFH_ou2qpgETg0RTNUPlDlOlM8qZve5Vpxt375zVbCv5TE1Y3xSZFczF8pUnhliW432x-STH6ttXpjLH6VerZYpD8Njz3xdmtRHPhnKh47p-d-z5GURRi9ZloA2gNjAd7PT2ZDPY-OUFhHwqZmKOsNo60gLvOOfSojlWMEtgRzfzgZvGUquvlfrDcgfWYmWHz3d1V3XnuuMN2lZFrAXymOFickL8uuuPR-2xaP3yfWPQb50wkO-tBOVvbRyNb4Ld35jORTKKGFxF4dDO_t6aD_itlrVt67vAk9MXUmzpU5h27mBu7T6BsqYNH-ChitcG1dIUS1Ua-ulMbSpjAwdU1Eozq5hllGwARSeyATTlqmuvGrssGdhTlZliD7y6kb3Pc2y8biTUMXux5A7OrbNJFrUb3qoqlTR84CJIe_W-HhVyF8ZpuyB7B-MqyiP4o1spLiAiHcpNebZlu2O2oxphpbcuo69XEpNRCg1j6VBtrNDavuOlIc5nnGg=w972-h548-s-no?authuser=0


# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: andrii.romanenko.js@gmail.com
facebook_username: AndreylovesGod
twitter_username: brilliantic1
instagram_username: romanenko_ipo
linkedin_username: romanenko--andrii
github_username:  brilliantic
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Interesting fact
# URL for the Image of the Author
author-image: https://github.com/brilliantic/My_Portfolio/blob/master/assets/images/I'm_and_cat.jpg?raw=true
# 60 Words About the Author
author-about: I can't pass by a cat. I have to pet it.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/romanenko--andrii/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
